import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { ColorPalette, ColorPaletteFormData, DEFAULT_PALETTE } from '@/types/theme';
import { hexToHsl, autoGenerateDarkColors, getAccessibleTextColor } from '@/lib/theme-utils';
import { extractComputedColors } from '@/lib/css-extractor';
import { apiClient } from '@/lib/api';

interface ThemeState {
  palette: ColorPalette | null;
  palettes: ColorPalette[];
  isLoading: boolean;
  error: string | null;
  appliedFromCss: boolean; // Track if CSS was applied first
  _isFetching: boolean; // Internal flag to prevent double fetches

  // Actions
  setPalette: (palette: ColorPalette) => void;
  setPalettes: (palettes: ColorPalette[]) => void;
  createPalette: (data: ColorPaletteFormData) => Promise<void>;
  updatePalette: (id: number, data: ColorPaletteFormData) => Promise<void>;
  deletePalette: (id: number) => Promise<void>;
  setDefaultPalette: (id: number) => Promise<void>;
  fetchPalettes: () => Promise<void>;
  fetchActivePalette: () => Promise<void>;
  applyPaletteToDom: (palette: ColorPalette) => void;
  applyDefaultsFromCss: () => void; // New: apply CSS defaults first
  clearError: () => void;
}

// Build CSS variables block from a color set (hex values → HSL component strings)
const buildCssVarBlock = (colors: {
  primary: string;
  secondary: string;
  destructive: string;
  muted: string;
  accent: string;
  foreground: string;
  background: string;
  card: string;
  cardForeground: string;
  popover: string;
  popoverForeground: string;
  border: string;
  input: string;
  ring: string;
  chartOne: string;
  chartTwo: string;
  chartThree: string;
  chartFour: string;
  chartFive: string;
}): string => {
  const h = hexToHsl;
  const textOn = (background: string, preferred?: string) =>
    h(getAccessibleTextColor(background, preferred));
  return [
    `--primary: ${h(colors.primary)}`,
    `--primary-foreground: ${textOn(colors.primary)}`,
    `--secondary: ${h(colors.secondary)}`,
    `--secondary-foreground: ${textOn(colors.secondary)}`,
    `--destructive: ${h(colors.destructive)}`,
    `--destructive-foreground: ${textOn(colors.destructive)}`,
    `--muted: ${h(colors.muted)}`,
    `--muted-foreground: ${textOn(colors.muted)}`,
    `--accent: ${h(colors.accent)}`,
    `--accent-foreground: ${textOn(colors.accent)}`,
    `--foreground: ${textOn(colors.background, colors.foreground)}`,
    `--background: ${h(colors.background)}`,
    `--card: ${h(colors.card)}`,
    `--card-foreground: ${textOn(colors.card, colors.cardForeground)}`,
    `--popover: ${h(colors.popover)}`,
    `--popover-foreground: ${textOn(colors.popover, colors.popoverForeground)}`,
    `--border: ${h(colors.border)}`,
    `--input: ${h(colors.input)}`,
    `--ring: ${h(colors.ring)}`,
    `--chart-1: ${h(colors.chartOne)}`,
    `--chart-2: ${h(colors.chartTwo)}`,
    `--chart-3: ${h(colors.chartThree)}`,
    `--chart-4: ${h(colors.chartFour)}`,
    `--chart-5: ${h(colors.chartFive)}`,
  ].map(line => `  ${line};`).join('\n');
};

export const useThemeStore = create<ThemeState>()(
  persist(
    (set, get) => ({
      palette: null,
      palettes: [],
      isLoading: false,
      error: null,
      appliedFromCss: false,
      _isFetching: false,

      setPalette: (palette: ColorPalette) => {
        set({ palette });
        get().applyPaletteToDom(palette);
      },

      setPalettes: (palettes: ColorPalette[]) => set({ palettes }),

      createPalette: async (data: ColorPaletteFormData) => {
        set({ isLoading: true, error: null });
        try {
          const newPalette = await apiClient.theme.palettes.create(data);
          set((state) => ({
            palettes: [...state.palettes, newPalette],
            isLoading: false,
          }));
        } catch (error) {
          const errorMsg = error instanceof Error ? error.message : 'Unknown error';
          console.error('Create palette error:', errorMsg);
          set({
            error: errorMsg,
            isLoading: false,
          });
          throw error;
        }
      },

      updatePalette: async (id: number, data: ColorPaletteFormData) => {
        set({ isLoading: true, error: null });
        try {
          const updated = await apiClient.theme.palettes.update(id, data);
          set((state) => ({
            palette: state.palette?.id === id || updated.isDefault ? updated : state.palette,
            palettes: state.palettes.map((p) => (p.id === id ? updated : p)),
            isLoading: false,
          }));
          if (updated.isDefault || get().palette?.id === id) {
            get().applyPaletteToDom(updated);
          }
        } catch (error) {
          const errorMsg = error instanceof Error ? error.message : 'Unknown error';
          console.error('Update palette error:', errorMsg);
          set({
            error: errorMsg,
            isLoading: false,
          });
          throw error;
        }
      },

      deletePalette: async (id: number) => {
        set({ isLoading: true, error: null });
        try {
          await apiClient.theme.palettes.remove(id);
          set((state) => ({
            palettes: state.palettes.filter((p) => p.id !== id),
            isLoading: false,
          }));
        } catch (error) {
          set({
            error: error instanceof Error ? error.message : 'Unknown error',
            isLoading: false,
          });
          throw error;
        }
      },

      setDefaultPalette: async (id: number) => {
        set({ isLoading: true, error: null });
        try {
          const updated = await apiClient.theme.palettes.setDefault(id);
          set((state) => ({
            palette: updated,
            palettes: state.palettes.map((p) => ({
              ...p,
              isDefault: p.id === id,
            })),
            isLoading: false,
          }));
          // Apply theme changes immediately
          Promise.resolve().then(() => get().applyPaletteToDom(updated));
        } catch (error) {
          const errorMsg = error instanceof Error ? error.message : 'Unknown error';
          console.error('Set default palette error:', errorMsg);
          set({
            error: errorMsg,
            isLoading: false,
          });
          throw error;
        }
      },

      fetchPalettes: async () => {
        // Prevent concurrent fetches
        if (get()._isFetching) return;

        set({ isLoading: true, error: null, _isFetching: true });
        try {
          const data = await apiClient.theme.palettes.list();
          set({ palettes: data, isLoading: false, _isFetching: false });
        } catch (error) {
          set({
            error: error instanceof Error ? error.message : 'Unknown error',
            isLoading: false,
            _isFetching: false,
          });
          throw error;
        }
      },

      fetchActivePalette: async () => {
        // Prevent concurrent fetches of active palette
        const state = get();
        if (state._isFetching || state.palette !== null) return;

        set({ isLoading: true, error: null, _isFetching: true });
        try {
          const data = await apiClient.theme.palettes.active();
          set({ palette: data, isLoading: false, _isFetching: false });
          // Defer DOM application to next microtask to avoid race conditions
          Promise.resolve().then(() => get().applyPaletteToDom(data));
        } catch (error) {
          const fallbackPalette = {
            id: 0,
            ...DEFAULT_PALETTE,
            isDefault: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          };
          set({
            error: error instanceof Error ? error.message : 'Unknown error',
            isLoading: false,
            palette: fallbackPalette,
            _isFetching: false,
          });
          // Defer DOM application to next microtask
          Promise.resolve().then(() => get().applyPaletteToDom(fallbackPalette));
        }
      },

      applyDefaultsFromCss: () => {
        // Extract current CSS variable values from globals.css
        const cssColors = extractComputedColors();

        if (Object.keys(cssColors).length > 0) {
          // Apply the CSS defaults to state for reference
          set({ appliedFromCss: true });
          // CSS is already applied via globals.css, nothing to inject
        }
      },

      applyPaletteToDom: (palette: ColorPalette) => {
        if (typeof document === 'undefined') return;

        // Build light mode colors from palette
        const lightColors = {
          primary: palette.primary,
          secondary: palette.secondary,
          destructive: palette.destructive,
          muted: palette.muted,
          accent: palette.accent,
          foreground: palette.foreground,
          background: palette.background,
          card: palette.card,
          cardForeground: palette.cardForeground,
          popover: palette.popover,
          popoverForeground: palette.popoverForeground,
          border: palette.border,
          input: palette.input,
          ring: palette.ring,
          chartOne: palette.chartOne,
          chartTwo: palette.chartTwo,
          chartThree: palette.chartThree,
          chartFour: palette.chartFour,
          chartFive: palette.chartFive,
        };

        // Build dark mode colors: merge auto-generated with admin overrides
        const autoDark = autoGenerateDarkColors(lightColors);
        const adminDark = palette.darkColors || {};
        const darkColors = {
          primary: adminDark.primary || autoDark.primary || palette.primary,
          secondary: adminDark.secondary || autoDark.secondary || palette.secondary,
          destructive: adminDark.destructive || autoDark.destructive || palette.destructive,
          muted: adminDark.muted || autoDark.muted || palette.muted,
          accent: adminDark.accent || autoDark.accent || palette.accent,
          foreground: adminDark.foreground || autoDark.foreground || palette.foreground,
          background: adminDark.background || autoDark.background || palette.background,
          card: adminDark.card || autoDark.card || palette.card,
          cardForeground: adminDark.cardForeground || autoDark.cardForeground || palette.cardForeground,
          popover: adminDark.popover || autoDark.popover || palette.popover,
          popoverForeground: adminDark.popoverForeground || autoDark.popoverForeground || palette.popoverForeground,
          border: adminDark.border || autoDark.border || palette.border,
          input: adminDark.input || autoDark.input || palette.input,
          ring: adminDark.ring || autoDark.ring || palette.ring,
          chartOne: adminDark.chartOne || autoDark.chartOne || palette.chartOne,
          chartTwo: adminDark.chartTwo || autoDark.chartTwo || palette.chartTwo,
          chartThree: adminDark.chartThree || autoDark.chartThree || palette.chartThree,
          chartFour: adminDark.chartFour || autoDark.chartFour || palette.chartFour,
          chartFive: adminDark.chartFive || autoDark.chartFive || palette.chartFive,
        };

        // Inject <style> tag instead of inline styles.
        // This allows .dark { } to properly override :root { }
        const styleId = 'palette-theme';
        let styleEl = document.getElementById(styleId) as HTMLStyleElement | null;
        if (!styleEl) {
          styleEl = document.createElement('style');
          styleEl.id = styleId;
          document.head.appendChild(styleEl);
        }

        styleEl.textContent = `:root {\n${buildCssVarBlock(lightColors)}\n}\n\n.dark {\n${buildCssVarBlock(darkColors)}\n}`;

        // Store palette ID for reference
        localStorage.setItem('applied-palette-id', String(palette.id));
      },

      clearError: () => set({ error: null }),
    }),
    {
      name: 'theme-store',
      storage: createJSONStorage(() => localStorage),
    }
  )
);
