import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Sun, Moon, ChevronDown, ChevronUp, Wand2, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ColorPaletteFormData, DarkColorOverrides } from '@/types/theme';

interface EditingPalette extends ColorPaletteFormData {
  id?: string;
}

const COLOR_FIELDS = [
  { key: 'primary', label: 'Primary' },
  { key: 'secondary', label: 'Secondary' },
  { key: 'destructive', label: 'Destructive' },
  { key: 'accent', label: 'Accent' },
  { key: 'muted', label: 'Muted' },
  { key: 'foreground', label: 'Foreground' },
  { key: 'background', label: 'Background' },
  { key: 'card', label: 'Card' },
  { key: 'cardForeground', label: 'Card Foreground' },
  { key: 'popover', label: 'Popover' },
  { key: 'popoverForeground', label: 'Popover Foreground' },
  { key: 'border', label: 'Border' },
  { key: 'input', label: 'Input' },
  { key: 'ring', label: 'Ring' },
  { key: 'chartOne', label: 'Chart 1' },
  { key: 'chartTwo', label: 'Chart 2' },
  { key: 'chartThree', label: 'Chart 3' },
  { key: 'chartFour', label: 'Chart 4' },
  { key: 'chartFive', label: 'Chart 5' },
];

interface ColorPaletteFormProps {
  editingId: string | null;
  formData: EditingPalette;
  setFormData: React.Dispatch<React.SetStateAction<EditingPalette>>;
  showDarkColors: boolean;
  setShowDarkColors: (show: boolean) => void;
  darkFormData: DarkColorOverrides;
  setDarkFormData: React.Dispatch<React.SetStateAction<DarkColorOverrides>>;
  isLoading: boolean;
  handleSave: () => Promise<void>;
  handleCancel: () => void;
  handleColorChange: (key: string, value: string) => void;
  handleDarkColorChange: (key: string, value: string) => void;
  handleAutoGenerateDark: () => void;
}

export function ColorPaletteForm({
  editingId,
  formData,
  setFormData,
  showDarkColors,
  setShowDarkColors,
  darkFormData,
  setDarkFormData,
  isLoading,
  handleSave,
  handleCancel,
  handleColorChange,
  handleDarkColorChange,
  handleAutoGenerateDark
}: ColorPaletteFormProps) {
  return (
    <motion.div
      className="w-full max-w-4xl max-h-[90vh] overflow-y-auto bg-background rounded-xl border border-border/20 shadow-xl p-6"
      initial={{ y: 20 }}
      animate={{ y: 0 }}
    >
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-2xl font-bold text-foreground">
          {editingId ? 'Edit Palette' : 'Create New Palette'}
        </h3>
        <button
          onClick={handleCancel}
          className="p-2 hover:bg-muted rounded-md transition-colors"
        >
          <X className="h-5 w-5" />
        </button>
      </div>

      {/* Palette Name */}
      <div className="mb-6">
        <Label htmlFor="name" className="text-base font-semibold mb-2 block">
          Palette Name
        </Label>
        <Input
          id="name"
          value={formData.name}
          onChange={(e) => setFormData((prev) => ({ ...prev, name: e.target.value }))}
          placeholder="e.g., Ocean Blue, Sunset Orange"
          className="w-full"
        />
      </div>

      {/* Light Mode Color Grid */}
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-3">
          <Sun className="h-4 w-4 text-amber-500" />
          <h4 className="text-base font-semibold text-foreground">Light Mode Colors</h4>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {COLOR_FIELDS.map((field) => (
            <div key={field.key} className="space-y-2">
              <Label htmlFor={field.key} className="text-sm font-medium">
                {field.label}
              </Label>
              <div className="flex items-center gap-2">
                <input
                  id={field.key}
                  type="color"
                  value={(formData as Record<string, any>)[field.key] || '#000000'}
                  onChange={(e) => handleColorChange(field.key, e.target.value)}
                  className="w-12 h-10 rounded-md cursor-pointer border border-border/20"
                />
                <Input
                  type="text"
                  value={(formData as Record<string, any>)[field.key] || ''}
                  onChange={(e) => handleColorChange(field.key, e.target.value)}
                  className="flex-1 font-mono text-sm"
                  placeholder="#000000"
                />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Dark Mode Section */}
      <div className="mb-6 border border-border/20 rounded-lg overflow-hidden">
        <button
          type="button"
          onClick={() => setShowDarkColors(!showDarkColors)}
          className="w-full flex items-center justify-between p-4 hover:bg-muted/50 transition-colors"
        >
          <div className="flex items-center gap-2">
            <Moon className="h-4 w-4 text-primary" />
            <span className="text-base font-semibold text-foreground">Dark Mode Colors</span>
            {Object.keys(darkFormData).length > 0 && (
              <Badge variant="secondary" className="text-xs">
                {Object.keys(darkFormData).length} overrides
              </Badge>
            )}
          </div>
          {showDarkColors ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
        </button>

        <AnimatePresence>
          {showDarkColors && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="overflow-hidden"
            >
              <div className="p-4 border-t border-border/20 bg-muted/30">
                <div className="flex items-center gap-2 mb-4">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={handleAutoGenerateDark}
                  >
                    <Wand2 className="mr-2 h-3 w-3" />
                    Auto-Generate from Light
                  </Button>
                  {Object.keys(darkFormData).length > 0 && (
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={() => setDarkFormData({})}
                      className="text-destructive"
                    >
                      Clear All
                    </Button>
                  )}
                  <p className="text-xs text-muted-foreground ml-auto">
                    Leave empty to auto-generate
                  </p>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {COLOR_FIELDS.map((field) => (
                    <div key={`dark-${field.key}`} className="space-y-2">
                      <Label htmlFor={`dark-${field.key}`} className="text-sm font-medium">
                        {field.label}
                      </Label>
                      <div className="flex items-center gap-2">
                        <input
                          id={`dark-${field.key}`}
                          type="color"
                          value={(darkFormData as Record<string, any>)[field.key] || (formData as Record<string, any>)[field.key] || '#000000'}
                          onChange={(e) => handleDarkColorChange(field.key, e.target.value)}
                          className="w-12 h-10 rounded-md cursor-pointer border border-border/20"
                        />
                        <Input
                          type="text"
                          value={(darkFormData as Record<string, any>)[field.key] || ''}
                          onChange={(e) => handleDarkColorChange(field.key, e.target.value)}
                          className="flex-1 font-mono text-sm"
                          placeholder={`Auto (from light)`}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Actions */}
      <div className="flex justify-end gap-3">
        <Button variant="outline" onClick={handleCancel}>
          Cancel
        </Button>
        <Button onClick={handleSave} disabled={isLoading}>
          <Save className="mr-2 h-4 w-4" />
          {isLoading ? 'Saving...' : 'Save Palette'}
        </Button>
      </div>
    </motion.div>
  );
}
