'use client';

import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Trash2, Plus, Palette, Save, X, Moon, Sun, ChevronDown, ChevronUp, Wand2 } from 'lucide-react';
import { useThemeStore } from '@/store/useThemeStore';
import { GlassCard, GlassCardContent, GlassCardDescription, GlassCardHeader, GlassCardTitle } from '@/components/ui/glass-card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ColorPalette, ColorPaletteFormData, DarkColorOverrides, DEFAULT_PALETTE } from '@/types/theme';
import { autoGenerateDarkColors, getAccessibleTextColor, isValidHexColor } from '@/lib/theme-utils';
import { cn } from '@/lib/utils';

import { ColorPaletteForm } from './form';

const PAIRED_FOREGROUNDS: Record<string, 'foreground' | 'cardForeground' | 'popoverForeground'> = {
  background: 'foreground',
  card: 'cardForeground',
  popover: 'popoverForeground',
};

const toFormData = (palette: ColorPalette): ColorPaletteFormData => ({
  name: palette.name,
  primary: palette.primary,
  secondary: palette.secondary,
  destructive: palette.destructive,
  muted: palette.muted,
  accent: palette.accent,
  foreground: palette.foreground,
  background: palette.background,
  card: palette.card,
  cardForeground: palette.cardForeground,
  popover: palette.popover,
  popoverForeground: palette.popoverForeground,
  border: palette.border,
  input: palette.input,
  ring: palette.ring,
  chartOne: palette.chartOne,
  chartTwo: palette.chartTwo,
  chartThree: palette.chartThree,
  chartFour: palette.chartFour,
  chartFive: palette.chartFive,
  glassBg: palette.glassBg ?? palette.card,
  glassBorder: palette.glassBorder ?? palette.border,
  darkColors: palette.darkColors ?? null,
});

const alertApiError = (action: string, error: unknown) => {
  const message = error instanceof Error ? error.message : 'Terjadi kesalahan yang tidak diketahui.';
  window.alert(`${action} gagal.\n\n${message}`);
};

export default function ColorPaletteView() {
  const { palettes, palette, isLoading, error, createPalette, updatePalette, deletePalette, setDefaultPalette, fetchPalettes } = useThemeStore();
  const [isEditing, setIsEditing] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [formData, setFormData] = useState<ColorPaletteFormData>(DEFAULT_PALETTE);
  const [showDarkColors, setShowDarkColors] = useState(false);
  const [darkFormData, setDarkFormData] = useState<DarkColorOverrides>({});

  // Fetch palettes only once on mount
  useEffect(() => {
    const load = async () => {
      try {
        await fetchPalettes();
      } catch (error) {
        console.error('Failed to load palettes:', error);
        alertApiError('Memuat color palette', error);
      }
    };
    void load();
  }, []);

  const handleCreateNew = () => {
    setFormData({ ...DEFAULT_PALETTE });
    setDarkFormData({});
    setEditingId(null);
    setIsEditing(true);
    setShowDarkColors(false);
  };

  const handleEdit = (selectedPalette: ColorPalette) => {
    setFormData(toFormData(selectedPalette));
    setDarkFormData(selectedPalette.darkColors || {});
    setEditingId(Number(selectedPalette.id));
    setIsEditing(true);
    setShowDarkColors(!!selectedPalette.darkColors && Object.keys(selectedPalette.darkColors).length > 0);
  };

  const handleSave = async () => {
    if (!formData.name.trim()) {
      alert('Please enter a palette name');
      return;
    }

    try {
      const saveData: ColorPaletteFormData = {
        ...formData,
        darkColors: showDarkColors && Object.keys(darkFormData).length > 0 ? darkFormData : null,
      };

      if (editingId !== null) {
        await updatePalette(editingId, saveData);
      } else {
        await createPalette(saveData);
      }

      setIsEditing(false);
      setEditingId(null);
      setFormData(DEFAULT_PALETTE);
      setDarkFormData({});
    } catch (error) {
      console.error('Save error:', error);
      alertApiError(editingId !== null ? 'Memperbarui color palette' : 'Membuat color palette', error);
    }
  };

  const handleCancel = () => {
    setIsEditing(false);
    setEditingId(null);
    setFormData(DEFAULT_PALETTE);
    setDarkFormData({});
    setShowDarkColors(false);
  };

  const handleColorChange = (key: string, value: string) => {
    setFormData((previous) => {
      const next = { ...previous, [key]: value };
      const foregroundKey = PAIRED_FOREGROUNDS[key];

      if (foregroundKey && isValidHexColor(value)) {
        next[foregroundKey] = getAccessibleTextColor(value, previous[foregroundKey]);
      }

      return next;
    });
  };

  const handleDarkColorChange = (key: string, value: string) => {
    setDarkFormData((previous) => {
      const next = { ...previous, [key]: value };
      const foregroundKey = PAIRED_FOREGROUNDS[key];

      if (foregroundKey && isValidHexColor(value)) {
        next[foregroundKey] = getAccessibleTextColor(
          value,
          previous[foregroundKey] ?? formData[foregroundKey],
        );
      }

      return next;
    });
  };

  const handleAutoGenerateDark = () => {
    const generated = autoGenerateDarkColors(formData);
    setDarkFormData(generated);
    setShowDarkColors(true);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="space-y-6"
    >
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
        >
          <h2 className="text-3xl font-bold tracking-tight text-foreground">Color Palette Manager</h2>
          <p className="text-muted-foreground">Manage and customize color schemes for your application.</p>
        </motion.div>
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={handleCreateNew}
          className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2"
        >
          <Plus className="mr-2 h-4 w-4" /> Create Palette
        </motion.button>
      </div>

      {/* Error Display */}
      {error && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-4 bg-destructive/10 border border-destructive/20 rounded-lg text-destructive"
        >
          <p className="text-sm font-medium">Error: {error}</p>
        </motion.div>
      )}

      {/* Editor Modal */}
      <AnimatePresence>
        {isEditing && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"
          >
            <ColorPaletteForm 
              editingId={editingId}
              formData={formData}
              setFormData={setFormData}
              showDarkColors={showDarkColors}
              setShowDarkColors={setShowDarkColors}
              darkFormData={darkFormData}
              setDarkFormData={setDarkFormData}
              isLoading={isLoading}
              handleSave={handleSave}
              handleCancel={handleCancel}
              handleColorChange={handleColorChange}
              handleDarkColorChange={handleDarkColorChange}
              handleAutoGenerateDark={handleAutoGenerateDark}
            />
          </motion.div>
        )}
      </AnimatePresence>

      {/* Palettes List */}
      <div className="grid gap-4">
        <AnimatePresence>
          {palettes.map((p, index) => (
            <motion.div
              key={p.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ delay: index * 0.05 }}
            >
              <GlassCard>
                <GlassCardHeader>
                  <div className="flex items-start justify-between">
                    <div className="flex items-center gap-3">
                      <Palette className="h-5 w-5 text-primary" />
                      <div>
                        <GlassCardTitle className="flex items-center gap-2">
                          {p.name}
                          {p.isDefault && <Badge className="bg-primary/20 text-primary">Active</Badge>}
                        </GlassCardTitle>
                        <GlassCardDescription>
                          Created {new Date(p.createdAt).toLocaleDateString()}
                        </GlassCardDescription>
                      </div>
                    </div>
                  </div>
                </GlassCardHeader>
                <GlassCardContent>
                  {/* Color Preview Grid */}
                  <div className="grid grid-cols-5 sm:grid-cols-10 gap-3 mb-4">
                    {[
                      { key: 'primary', value: p.primary },
                      { key: 'secondary', value: p.secondary },
                      { key: 'destructive', value: p.destructive },
                      { key: 'accent', value: p.accent },
                      { key: 'muted', value: p.muted },
                      { key: 'chartOne', value: p.chartOne },
                      { key: 'chartTwo', value: p.chartTwo },
                      { key: 'chartThree', value: p.chartThree },
                      { key: 'chartFour', value: p.chartFour },
                      { key: 'chartFive', value: p.chartFive },
                    ].map((item) => (
                      <div
                        key={item.key}
                        className="flex flex-col items-center gap-1"
                        title={item.key}
                      >
                        <div
                          className="w-10 h-10 rounded-md border border-border/20 shadow-sm"
                          style={{ backgroundColor: item.value }}
                        />
                        <span className="text-xs text-muted-foreground truncate">
                          {item.key.slice(0, 3)}
                        </span>
                      </div>
                    ))}
                  </div>

                  {/* Actions */}
                  <div className="flex gap-2">
                    {!p.isDefault && (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={async () => {
                          try {
                            await setDefaultPalette(p.id);
                          } catch (err) {
                            console.error('Failed to set default palette:', err);
                            alertApiError('Mengaktifkan color palette', err);
                          }
                        }}
                        disabled={isLoading}
                      >
                        {isLoading ? 'Setting...' : 'Set as Active'}
                      </Button>
                    )}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleEdit(p)}
                      disabled={isLoading}
                    >
                      Edit
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="text-destructive hover:text-destructive-foreground hover:bg-destructive/20"
                      onClick={async () => {
                        if (window.confirm('Are you sure? This action cannot be undone.')) {
                          try {
                            await deletePalette(p.id);
                          } catch (err) {
                            console.error('Failed to delete palette:', err);
                            alertApiError('Menghapus color palette', err);
                          }
                        }
                      }}
                      disabled={p.isDefault}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </GlassCardContent>
              </GlassCard>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      {palettes.length === 0 && !isLoading && (
        <GlassCard className="text-center py-12">
          <div className="text-muted-foreground mb-4">
            <Palette className="h-12 w-12 mx-auto opacity-50" />
          </div>
          <p className="text-muted-foreground mb-4">No color palettes yet. Create one to get started.</p>
          <Button onClick={handleCreateNew}>
            <Plus className="h-4 w-4 sm:mr-2" /> <span className="hidden sm:inline">Create First Palette</span></Button>
        </GlassCard>
      )}
    </motion.div>
  );
}
