// filepath: d:\Project\Arkanin_v1\ops\docker-compose.yml
version: '3.8'
services:
  api:
    build: ../apps/api
    ports:
      - "8000:8000"
    env_file:
      - ../apps/api/.env
  web:
    build: ../apps/web
    ports:
      - "3000:3000"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: edutech
      POSTGRES_USER: edutech
      POSTGRES_PASSWORD: edutech
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"