import { ColorPalette, DarkColorOverrides } from '@/types/theme';

/**
 * Convert hex color to bare HSL component string
 * e.g. "#5b61f5" → "243.8 90.5% 58.2%"
 */
export function hexToHsl(hex: string): string {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return '0 0% 0%';

  const r = parseInt(result[1], 16) / 255;
  const g = parseInt(result[2], 16) / 255;
  const b = parseInt(result[3], 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  const d = max - min;

  if (d === 0) {
    return `0 0% ${Math.round(l * 1000) / 10}%`;
  }

  const s = l > 0.5 ? d / (2 - max - min) : d / (max - min);
  let h = 0;
  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) * 60;
  else if (max === g) h = ((b - r) / d + 2) * 60;
  else h = ((r - g) / d + 4) * 60;

  return `${Math.round(h * 10) / 10} ${Math.round(s * 1000) / 10}% ${Math.round(l * 1000) / 10}%`;
}

/**
 * Convert HSL component string back to hex color
 * e.g. "243.8 90.5% 58.2%" → "#5b61f5"
 */
export function hslToHex(hslString: string): string {
  const parts = hslString.trim().split(/[\s%]+/).filter(p => p);
  if (parts.length < 3) return '#000000';

  const hue = parseFloat(parts[0]);
  const sat = parseFloat(parts[1]) / 100;
  const lit = parseFloat(parts[2]) / 100;

  const c = (1 - Math.abs(2 * lit - 1)) * sat;
  const hPrime = hue / 60;
  const x = c * (1 - Math.abs((hPrime % 2) - 1));
  let r = 0, g = 0, b = 0;

  if (hPrime >= 0 && hPrime < 1) { r = c; g = x; }
  else if (hPrime >= 1 && hPrime < 2) { r = x; g = c; }
  else if (hPrime >= 2 && hPrime < 3) { g = c; b = x; }
  else if (hPrime >= 3 && hPrime < 4) { g = x; b = c; }
  else if (hPrime >= 4 && hPrime < 5) { r = x; b = c; }
  else if (hPrime >= 5 && hPrime <= 6) { r = c; b = x; }

  const m = lit - c / 2;
  const rH = Math.round((r + m) * 255).toString(16).padStart(2, '0');
  const gH = Math.round((g + m) * 255).toString(16).padStart(2, '0');
  const bH = Math.round((b + m) * 255).toString(16).padStart(2, '0');

  return `#${rH}${gH}${bH}`;
}

/**
 * Adjust lightness of a hex color
 * @param hex - hex color string
 * @param targetLightness - target lightness (0-100)
 */
function adjustLightness(hex: string, targetLightness: number): string {
  const hsl = hexToHsl(hex);
  const parts = hsl.split(/[\s%]+/).filter(p => p);
  if (parts.length < 3) return hex;
  const h = parseFloat(parts[0]);
  const s = parseFloat(parts[1]);
  return hslToHex(`${h} ${s}% ${targetLightness}%`);
}

/**
 * Auto-generate dark mode colors from a light palette.
 * Follows WCAG contrast best practices:
 * - Backgrounds become very dark (L: 4-10%)
 * - Foreground text becomes light (L: 90-98%)
 * - Primary/accent colors keep hue but boost lightness for dark bg
 * - Borders/muted become subtle dark tones
 */
export function autoGenerateDarkColors(lightPalette: {
  primary: string;
  secondary: string;
  destructive: string;
  muted: string;
  accent: string;
  foreground: string;
  background: string;
  card: string;
  cardForeground: string;
  popover: string;
  popoverForeground: string;
  border: string;
  input: string;
  ring: string;
  chartOne: string;
  chartTwo: string;
  chartThree: string;
  chartFour: string;
  chartFive: string;
}): DarkColorOverrides {
  // Parse light primary hue for consistent dark generation
  const primaryHsl = hexToHsl(lightPalette.primary);
  const primaryParts = primaryHsl.split(/[\s%]+/).filter(p => p);
  const primaryHue = parseFloat(primaryParts[0] || '0');

  return {
    // Keep hue, adjust for dark background visibility
    primary: adjustLightness(lightPalette.primary, 65),
    secondary: hslToHex(`${primaryHue} 15% 15%`),
    destructive: adjustLightness(lightPalette.destructive, 55),
    muted: hslToHex(`${primaryHue} 10% 18%`),
    accent: adjustLightness(lightPalette.accent, 60),

    // Invert fg/bg
    foreground: '#fafafa',
    background: hslToHex(`${primaryHue} 15% 6%`),
    card: hslToHex(`${primaryHue} 12% 9%`),
    cardForeground: '#fafafa',
    popover: hslToHex(`${primaryHue} 12% 9%`),
    popoverForeground: '#fafafa',

    // Subtle dark borders
    border: hslToHex(`${primaryHue} 10% 18%`),
    input: hslToHex(`${primaryHue} 10% 18%`),
    ring: adjustLightness(lightPalette.ring, 65),

    // Charts — boost lightness for dark bg
    chartOne: adjustLightness(lightPalette.chartOne, 65),
    chartTwo: adjustLightness(lightPalette.chartTwo, 65),
    chartThree: adjustLightness(lightPalette.chartThree, 65),
    chartFour: adjustLightness(lightPalette.chartFour, 65),
    chartFive: adjustLightness(lightPalette.chartFive, 65),
  };
}

/**
 * Convert color palette to CSS variables string
 * Values are stored as bare HSL components (e.g. "243.8 90.5% 58.2%")
 * to match Tailwind's hsl(var(--xxx)) pattern
 */
export function generateCSSVariables(palette: ColorPalette): string {
  const h = hexToHsl;
  return `
:root {
  --primary: ${h(palette.primary)};
  --primary-foreground: ${h(palette.cardForeground)};
  --secondary: ${h(palette.secondary)};
  --secondary-foreground: ${h(palette.cardForeground)};
  --destructive: ${h(palette.destructive)};
  --destructive-foreground: 0 0% 100%;
  --muted: ${h(palette.muted)};
  --muted-foreground: ${h(palette.cardForeground)};
  --accent: ${h(palette.accent)};
  --accent-foreground: 0 0% 100%;
  --foreground: ${h(palette.foreground)};
  --background: ${h(palette.background)};
  --card: ${h(palette.card)};
  --card-foreground: ${h(palette.cardForeground)};
  --popover: ${h(palette.popover)};
  --popover-foreground: ${h(palette.popoverForeground)};
  --border: ${h(palette.border)};
  --input: ${h(palette.input)};
  --ring: ${h(palette.ring)};
  --chart-1: ${h(palette.chartOne)};
  --chart-2: ${h(palette.chartTwo)};
  --chart-3: ${h(palette.chartThree)};
  --chart-4: ${h(palette.chartFour)};
  --chart-5: ${h(palette.chartFive)};
}
  `.trim();
}

/**
 * Export palette as JSON for backup/import
 */
export function exportPaletteAsJSON(palette: ColorPalette): string {
  return JSON.stringify(palette, null, 2);
}

/**
 * Export palette as JavaScript object
 */
export function exportPaletteAsJS(palette: ColorPalette): string {
  return `export const ${palette.name.replace(/\s+/g, '')}Palette = ${JSON.stringify(palette, null, 2)};`;
}

/**
 * Validate hex color format
 */
export function isValidHexColor(color: string): boolean {
  return /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(color);
}

/**
 * Convert hex to RGB
 */
export function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16),
    }
    : null;
}

/**
 * Generate complementary color
 */
export function getComplementaryColor(hex: string): string {
  const rgb = hexToRgb(hex);
  if (!rgb) return '#000000';

  const r = 255 - rgb.r;
  const g = 255 - rgb.g;
  const b = 255 - rgb.b;

  return `#${[r, g, b].map((x) => x.toString(16).padStart(2, '0')).join('').toUpperCase()}`;
}

/**
 * Generate contrasting text color (black or white)
 */
export function getContrastingTextColor(hex: string): string {
  const rgb = hexToRgb(hex);
  if (!rgb) return '#000000';

  const luminance = (rgb.r * 299 + rgb.g * 587 + rgb.b * 114) / 1000;
  return luminance > 128 ? '#000000' : '#FFFFFF';
}
